"""remove_chunk_text_store_in_blob

Revision ID: d2d008e51d95
Revises: 90c7d541ca8d
Create Date: 2025-10-21 18:43:56.587405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2d008e51d95'
down_revision: Union[str, None] = '90c7d541ca8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_chunks', 'blob_storage_path',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.drop_column('file_chunks', 'chunk_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_chunks', sa.Column('chunk_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.alter_column('file_chunks', 'blob_storage_path',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    # ### end Alembic commands ###
